### ISSUE TITLE
Cannot add image

### ISSUE THREAD

**Issue by arthur-s** [kriszyp/alkali#28]
This not work for me, cannot set src to image.
```javascript
import {Div, Span, Image, Variable} from 'alkali';

let PromoComp = new Div('.outer', [
	Image({src: '/img/wikipedia/wP.png'})
]);
```

Also, to the document appends `<image></image>`, but must `<img />`
Alkali version - 0.11.7

**Comment by kriszyp** [comment]
Thanks for the report. Should be fixed in v0.12.0.
