### ISSUE TITLE
Feature: isEmpty operator

### ISSUE THREAD

**Issue by kvcrawford** [kriszyp/alkali#36]
Equivalent to lodash's `isEmpty`: https://lodash.com/docs/4.17.4#isEmpty

**Comment by kriszyp** [comment]
Were you thinking `isEmpty` as an alkali export such that `isEmpty(variable) === variable.to(_.isEmpty)`? Or were you thinking some reversible capability like a lot of the operators?

**Comment by ahamid** [comment]
Thought: it should be feasible to curry operators so that `op(a, ...)` is also (always?) accessible as `a.op(...)`?

**Comment by kvcrawford** [comment]
I'm not sure what you mean by reversible capability?

**Comment by kriszyp** [comment]
Part of the reason most of the operators exist is for reversibility:
```
let a = new Variable(true)
// could be negated with:
let aNot = a.to(a => !a)
// but
aNot.put(true) // throws error
// whereas
let aNot = not(a)
aNot.put(true)
a.valueOf() -> false
```
Likewise, could easily just write:
```
let aIsEmpty = a.to(_.isEmpty)
```
But it isn't reversible... Unless you are asking just to save a 5 characters and so the transform above is just equivalent to `isEmpty(a)`?
```
let isEmpty = (v) => v.to(_.isEmpty)
```

**Comment by kvcrawford** [comment]
Ah! TIL. I didn't realize there was more going on with those operators. 

Yes, I think `a.to(_.isEmpty)` is sufficiently concise :)
