### ISSUE TITLE
Feature request: disregard/coalesce Promise values

### ISSUE THREAD

**Issue by ahamid** [kriszyp/alkali#40]
The fact that promise values are implicitly resolved in transforms largely solves the issue of dealing with them, however there still arises from time to time the case of some downstream consumer eagerly, non-reactively, forcing the resolution of a variable chain, and assuming the value it receives is not a wrapping promise.  When the value is not a promise, this works fine and is unremarkable, but if a Promise sneaks into the chain at any point, it can become very difficult to track down and currently requires breaking/bridging the reactivity.

This can be done explicitly with a simple utility, like:

```javascript
export default (variableYieldingPromise, initialValue) => {
  const outputVar = new Variable(initialValue)
  variableYieldingPromise.subscribe((e) => {
    Promise.resolve(e.value()).then((value) => outputVar.put(value))
  })
  return outputVar
}
```

However this is pretty clunky, and non-idiomatic.  It would be preferable if there were some idiomatic way to "consume"/coalesce Promises such that we have a guarantee to never see them (at least, never see an initial level of Promises - Promises are self-composable, so I would not expect to see a Promise yielding underlying value that is itself a Promise).

e.g.:

```javascript
var s = new Variable('z')
var v = s.as(VPromised)
assert.equal(v.valueOf(), 'z')
s.put(new Promise(function (r) {
    setTimeout(function() { r('a') }, 100)
}))
assert.equal(v.valueOf(), 'z')
return new Promise(setTimeout).then(function () {
    // still initial value
    assert.equal(v.valueOf(), 'z')
    return new Promise(function (r) { setTimeout(r, 110) }).then(function() {
        // should contain resolved value now
	assert.equal(v.valueOf(), 'a')
    })
})
```

See #41 for tests illustrating usage, and several unsuccessful stabs at an implementation

**Comment by ahamid** [comment]
Perhaps a consuming transform would be a simpler convention?
```
maybePromise.to(v => isPromise(v) ? v : undefined)
or
promised = v => isPromise(v) ? v : undefined
maybePromise.to(promised)
```

**Comment by kriszyp** [comment]
There are several approaches to this. I think we have talked about them, but to spell them:
1. Have a `subscribe` variant the waits until the variables new value/promise is resolved before delivering the event + value to the listener, so it can provide a resolved. This doesn't solve the issue of being able to access `valueOf` and always guarantee a non-promise value.
2. Alter the setting mechanism, `put`, to defer the variable update until after the provide promise is resolved.
3. Create a new variable construct that can live in a "two-state" scenario. I think this is what you are going for in the PR. Both of the possibilities above still preserve normal variable semantics and expectations of a variable having a single state, that changes and is accessible after a `put`. Having two-state variables seems remarkably complicated, and as you noted, it is somewhere between hard to impossible to track down all the different ways that variables can change and trying to maintain both states at once (I have no idea how this would be possible in situations where you assign a promise to an object that is underlying a variable, where the variable's property is supposed to be a two-state variable).

Fundamentally, the goal of returning the previous value of a variable when a (source) variable's current state is a pending promise means that we need to actually peer into, or preserve the history of the variable's prior state. And this requires active monitoring of the source variable.

I think that the initial "simple utility" you mentioned above, really is the most correct way to achieve this. This bridges options 1 and 2 by essentially subscribing and waiting for the result and composing a new variable that is actively set to the resolved value. And this forces the necessary active listening required to be able preserve and look into the past to see the prior state while the current state is a promise pending.

Certainly the most painful aspect of this utility is the fact that it can't clean itself up. It is creating an active listener that will stay pinned in memory, and keep all its source active and pinned in memory, until the subscriber is cancelled. But, without being able to predict when possible future accesses might want the value right before the current pending value, there is no other way deterministic way than active management, as far as I can tell.

**Comment by ahamid** [comment]
Thanks @kriszyp, I came to the same realization re: the three possibilities listed above, and you're right an explicit subscription and assignment is the simplest; I implemented this as a simple helper in my second commit here a80db0023b70ee5aea61137aa9cc2bbc93df3812 but I'm fine continuing to keep it as a consumer side utility (maybe I can just mix in to the Variable prototype).  The marginal benefit of having in-situ support for Promise coalescing may be that Promises pushed into the target would be coalesced as well (e.g. in the utility above putting a promise into the output would break it all over again). I think all these approaches require some foreknowledge of where Promises can appear, so injecting a Promise in an unexpected point in the chain without explicitly coalescing can cause trouble again for an unexpecting consumer, but there probably isn't a solution to that other than a flag that affects global alkali behavior.
Unless you want to take `asPromised()` I think this request can be closed.
Thanks.

**Comment by kriszyp** [comment]
I think I am starting come around more to sharing your concerns about this. In particular, looking at the typing structures around alkali, the ability for promises to be returned from any `valueOf()` deeply undermines the type system. I am wondering if rather than a separate variable entity, we actually need to change the behavior of all Variables to never return promises from `valueOf()`.

I think your approach have separate "promised" and "resolved" values on a variable is the right way to do this. In addition, I think we should have two separate variable resolution paths, the synchronous one: `valueOf()`, and the async one: `then()`. This would work transitively, calling the corresponding versions on upstream variables for resolution as well. But basically, the `valueOf()` should always be sync (and `then` is for explicitly for requesting the eventual resolution). 

From a typing perspective, we would be saying that Variable's type definition would now be:
```
class Variable<T> {
    constructor(value?: T | Promise<T>)
    put(value: T | Variable<T> | Promise<T>)

```
And VPromise would go away, there is no use for a special variable class for promises, since any Variable can handle promises as input (from an implementation perspective, that is already true).

I wanted to think through the implications of this, and what the behavior should be for variables that have promises in provided values or upstream values.
```
let v = new Variable(promiseThatWillLaterResolveTo3)
v.valueOf() -> undefined (until promise is resolved)
// after resolution
v.valueOf() -> 3
// and then, if we do a put with a promise
v.put(promiseThatWillLaterResolveTo5)
v.valueOf() -> 3 // continues to return 3 until the promise resolves... or should it return undefined?
// after resolution
v.valueOf() -> 5
```
Object properties:
```
let o = {}
let v = new Variable(o)
let foo = v.property('foo')
foo.put(promiseThatWillLaterResolveTo3)
o.foo -> // will not affect underlying object until it the promise resolved
// after resolution
o.foo -> 3
// assigning directly to object behind alkali:
let o: {foo: Promise<number>} = {foo: promiseThatWillLaterResolveTo3}
let v = new Variable(o) // assuming we can genericize on the full type structure
// in this case, the parameterized type of the variable is no longer a number, it is actually a promise, and so I think we maybe *should* return a promise from valueOf()
v.property('foo').valueOf() -> promiseThatWillLaterResolveTo3
```
Also, I think it would be logical, if we did this, to shift `subscribe` to calling the callback once it has a resolved value (and handing over the resolved value).

What do you think?

**Comment by ahamid** [comment]
I do like your proposal.  Preserving the current value (while promise value is "pending") is what I would want, and what I wasn't able to succeed in prototyping.
I'm ambivalent about the property reflecting the original promise value on explicit assignment, but I think there is a rationale.
Playing devil's advocate, as a user I don't think it's ever been valuable to me to actually observe a promise.  In general I don't think having a promise is useful from a data flow perspective, but the one possibly useful counter-case I can imagine is to `cancel` the promise.  I think this would require the kind of support you're proposing anyway (preserve existing value, avoid the update).

**Comment by kriszyp** [comment]
Branched this off here: #42

**Comment by ahamid** [comment]
I think this is fulfilled by latest Alkali release, thanks! :+1:
