### ISSUE TITLE
Generating dynamic class name

### ISSUE THREAD

**Issue by arthur-s** [kriszyp/alkali#43]
Hello, I'm creating a MyButton class as:
```
class MyButton extends Div('.my-morphing-button', {
    caption: Variable,
    close_caption: Variable,
    body: Variable,
    modal_num: Variable,
}){
    created(properties)....
```
And I want to use modal_num for child Div's class name like:
```
MyButton.children = [
    Div('.morph-button-modal-`${MorphButton.modal_num}`', [ /*doesn't work for class name*/
        MorphButton.modal_num  /*but works for content*/
    ])
]
```
But I can't set desired number to the class name. How to fix it?.. (Is it possible?)
Thanks in advance

**Comment by kriszyp** [comment]
By putting the variable in template string, you are converting it to a string that is evaluated statically (before any instances of MyButton are created). I am not sure if you need `modal_num` to be reactive (can it change after the instance is created?). But off the top of my maybe you could do:
```
   Div({
     class: MorphButton.modal_num.to(num => '.morph-button-modal-`${num}`') 
   }, [
        MorphButton.modal_num  /*but works for content*/
    ])
```

**Comment by arthur-s** [comment]
Hi @kriszyp, Thanks again helping me. Your suggestion works well in version `0.16.0`, but it doesn't work in `0.16.1`.

**Comment by arthur-s** [comment]
Wait, I'll do more tests, and report you

**Comment by kriszyp** [comment]
I can take a look. I actually think that the 0.15.x versions might be a little more stable, did some refactoring for the 0.16.x versions, that may still have some issues.

**Comment by arthur-s** [comment]
sorry for late response, I've quickly checked, 0.15.12 version works well.
0.16.x works on PC with CentOS and nodejs version v6.10.2
0.16.x doesn't work on PC with Ubuntu 14 and nodejs version v6.11.1

Saying that it doesn't work, I meant this:
I have two buttons, `buttonA` opens modal window with class `my-modal-1`, and `button2` should open modal with `my-modal-2` - but second button still opens with `my-modal-1`.

**Comment by kriszyp** [comment]
Issue in 0.16.x should be fixed with https://github.com/kriszyp/alkali/commit/50f8079172786c3b9cc3d4105cc83a05092523d6.
