### ISSUE TITLE
Updating property with key of empty string fails to trigger updates

### ISSUE THREAD

**Issue by kvcrawford** [kriszyp/alkali#6]
```js
let foo = new Variable({'': 'foo'})

foo.get('')
// -> 'foo'

foo.property('').subscribe((event) => {
  console.log(event.value())
})

foo.set('', 'wat')
foo.property('').put('does it blend?')
// nothing happens, the subscribed event handler never fires.
```

This issue came up when using variables to represent selection state hashes, and some (selectable) values come up as empty string.

This works but it also triggers updaters for the entire object, rather than just that 1 property:

```js
foo.set('', 'wat') && foo.property('').updated()
```

**Comment by kvcrawford** [comment]
It could possibly happen with any false-y key:

```js 
foo.set(false, 'wat')
foo.set(0, 'wat')
```

**Comment by ahamid** [comment]
I think the problematic line is https://github.com/kriszyp/alkali/blob/0fff5ff30e5d722c0437b304fab40929f9fab24b/Variable.js#L159

```javascript
var property = propertyName && this._properties && this._properties[propertyName]
if (property && !(type instanceof PropertyChange) && object === this.valueOf()) {
	property.parentUpdated(ToChild, context)
}
```

`propertyName` is falsey in this case.  Changing the test to this instead appears to fix this specific case (I only tested in console):

`var property = propertyName != null && this._properties && this._properties[propertyName]`

If I have time this week I can write a test case and fix.
