### ISSUE TITLE
Missing standard element: Fieldset

### ISSUE THREAD

**Issue by kvcrawford** [kriszyp/alkali#61]
Requesting [Fieldset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) to be added to standard elements.

**Comment by kvcrawford** [comment]
@kriszyp I don't think it's working, does it need to be included in the `generate` function here? https://github.com/kriszyp/alkali/blob/master/Element.js#L1118

**Comment by kriszyp** [comment]
Oops, sorry about, should be fixed with the latest commit/version.
