### ISSUE TITLE
Suggestion: expose configurable change binding

### ISSUE THREAD

**Issue by ahamid** [kriszyp/alkali#7]
Text inputs are notoriously finicky for detecting changes reliably.  I had to supplement the default `bindChanges` functionality, as below, to respond to changes without waiting for a blur to occur:

```javascript
const ADDTL_TEXT_INPUT_CHANGE_EVENTS = [ 'propertychange', 'click', 'keyup', 'input', 'paste']
const textInput = new Variable()
const textInputCtrl = TextInput('.form-control', {
  type: 'text',
  name: 'name',
  created: function() {
    // try harder to detect changes eagerly
    const updateVar = () => { this.content.put(this['typedValue' in this ? 'typedValue' : 'value'], this) }
    for (const type of ADDTL_TEXT_INPUT_CHANGE_EVENTS) {
      this.addEventListener(type, updateVar)
    }
  }
}, this.textInput)
```

I'm wondering if this could be made configurable, or `bindChanges` added to the element prototype?

**Comment by kriszyp** [comment]
Yes, that makes sense.  Perhaps the immediate updates from each keystroke should be the default?
